# Generated by Django 4.1.2 on 2022-10-13 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='questionNumber',
            new_name='totalQuestion',
        ),
    ]
