# Generated by Django 4.1.2 on 2022-10-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='totalQuestion',
        ),
    ]
