# Generated by Django 4.1.2 on 2022-10-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_alter_courses_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='courseQuestion',
            field=models.CharField(default='empty', max_length=225),
        ),
    ]
