# Generated by Django 4.1.2 on 2022-10-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_question_coursequestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='courseQuestion',
            field=models.CharField(max_length=225),
        ),
    ]
