# Generated by Django 4.1.2 on 2022-10-11 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherSignup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('contact', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('profile', models.FileField(null=True, upload_to='media/')),
                ('username', models.CharField(max_length=100)),
                ('foreign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
