# Generated by Django 4.1.2 on 2022-10-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersignup',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
