# Generated by Django 4.1.2 on 2022-10-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_remove_teachersignup_foreign'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersignup',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teachersignup',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
