# Generated by Django 4.1.2 on 2022-10-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teachersignup_active_teachersignup_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersignup',
            name='active',
            field=models.CharField(default=False, max_length=225),
        ),
        migrations.AlterField(
            model_name='teachersignup',
            name='address',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='teachersignup',
            name='email',
            field=models.EmailField(max_length=225),
        ),
        migrations.AlterField(
            model_name='teachersignup',
            name='firstname',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='teachersignup',
            name='lastname',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='teachersignup',
            name='username',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
