# Generated by Django 4.1.2 on 2022-10-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_teachersignup_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersignup',
            name='active',
        ),
        migrations.AddField(
            model_name='teachersignup',
            name='activeTeacher',
            field=models.BooleanField(default=False),
        ),
    ]
