# Generated by Django 4.1.2 on 2022-10-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_remove_teachersignup_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersignup',
            name='activeTeacher',
            field=models.CharField(default='False', max_length=225),
        ),
    ]
