# Generated by Django 4.1.2 on 2022-10-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_teachersignup_activeteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersignup',
            name='activeTeacher',
            field=models.CharField(max_length=225),
        ),
    ]
