# Generated by Django 4.1.2 on 2022-10-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_alter_teachersignup_activeteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersignup',
            name='activeTeacher',
        ),
    ]
