# Generated by Django 4.1.2 on 2022-10-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='masterSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.TextField(max_length=100)),
                ('password', models.CharField(max_length=32)),
                ('contact', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('profile', models.FileField(null=True, upload_to='media/')),
            ],
        ),
    ]
