# Generated by Django 4.1.2 on 2022-10-10 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastersignup',
            name='password',
        ),
        migrations.RemoveField(
            model_name='mastersignup',
            name='username',
        ),
    ]
