# Generated by Django 4.1.2 on 2022-10-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_mastersignup_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersignup',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mastersignup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
