# Generated by Django 4.1.2 on 2022-10-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsignup',
            name='password',
        ),
        migrations.RemoveField(
            model_name='studentsignup',
            name='username',
        ),
    ]
