# Generated by Django 4.1.2 on 2022-10-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_studentsignup_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsignup',
            name='username',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentsignup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
