# Generated by Django 4.1.2 on 2022-10-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentsignup_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsignup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
